spring.application.name=catalogo
# URL de conexão (troque 'db_catalogo' pelo nome que você criou no pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo
spring.datasource.username=postgres
spring.datasource.password=123456
# Driver e Dialeto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate: 'update' cria as tabelas automaticamente se não existirem
spring.jpa.hibernate.ddl-auto=update

# Opcional: Mostra o SQL no console para você ver o que está acontecendo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
